[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
airdrop = "DATFQZy5MsVSwgj7TUdwRQdNCxsfGJfMvi9n3BP2zmac"

[programs.devnet]
airdrop = "DATFQZy5MsVSwgj7TUdwRQdNCxsfGJfMvi9n3BP2zmac"

[programs.mainnet]
airdrop = "DATFQZy5MsVSwgj7TUdwRQdNCxsfGJfMvi9n3BP2zmac"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/bingo/wallet-id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
